# Generated by Django 2.1.3 on 2019-06-26 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auther_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(default='', max_length=30, verbose_name='卡号')),
                ('card_user', models.CharField(default='', max_length=10, verbose_name='姓名')),
                ('card_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '银行卡账户_基本信息',
                'verbose_name_plural': '银行卡账户',
            },
        ),
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(default='', max_length=30, verbose_name='电话')),
                ('mail', models.EmailField(default='', max_length=30, verbose_name='邮箱')),
                ('city', models.CharField(default='', max_length=10, verbose_name='城市')),
                ('address', models.CharField(default='', max_length=30, verbose_name='详细地址')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Card', verbose_name='卡号')),
            ],
            options={
                'verbose_name': '账户_个人资料',
                'verbose_name_plural': '个人资料',
            },
        ),
    ]
